import type {
    GetRestaurantByQRCodeAJAXResponse,
    CreateQRCodeHashAJAXRequest,
    CreateQRCodeHashAJAXResponse,
} from 'type/api';
import { ajax } from 'coil-react';
// Attention: This file is generated by "yarn api", do not modify

export class ShareAJAXService {
    static getRestaurantByQRCode(hash: string): Promise<GetRestaurantByQRCodeAJAXResponse> {
        return ajax('GET', '/v1/share/:hash', { hash }, null);
    }

    static createQRCodeHash(request: CreateQRCodeHashAJAXRequest): Promise<CreateQRCodeHashAJAXResponse> {
        return ajax('POST', '/v1/share/', {}, request);
    }
}
