// Attention: This file is generated by "yarn api", do not modify

export interface GetRestaurantByQRCodeAJAXResponse {
    restaurants: GetRestaurantByQRCodeAJAXResponse$Restaurant[];
}
export interface GetRestaurantByQRCodeAJAXResponse$Restaurant {
    name: string;
    district: string[];
}
export interface CreateQRCodeHashAJAXRequest {
    restaurants: CreateQRCodeHashAJAXRequest$Restaurant[];
}
export interface CreateQRCodeHashAJAXRequest$Restaurant {
    name: string;
    district: string[];
}
export interface CreateQRCodeHashAJAXResponse {
    url: string;
}
